# Laravel کے لیے مناسب PHP image
FROM php:8.2-cli

# ورکنگ ڈائریکٹری
WORKDIR /var/www

# ضروری پیکجز انسٹال کریں
RUN apt-get update && apt-get install -y \
    zip unzip git curl libpng-dev libonig-dev libxml2-dev libzip-dev \
    && docker-php-ext-install pdo pdo_mysql mbstring exif pcntl zip

# Composer انسٹال کریں
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Laravel فائلز کاپی کریں
COPY . .

# Dependencies انسٹال کریں
RUN composer install --no-dev --optimize-autoloader

# permissions fix کریں
RUN chmod -R 755 /var/www/storage

# Laravel port expose کریں
EXPOSE 8000

# Laravel server + migrate
CMD php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000
